spring:
  application:
    name: kanban
  freemarker:
    cache: false
    suffix: .ftl
  web:
    resources:
      static-locations:
        - file:./src/main/resources/static/
        - classpath:/static/

server:
  http2:
    enabled: true

graphql:
  playground:
    enabled: true
